<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit904435d701a1655b4dcb389c24fce1ac
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Picqer\\Barcode\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Picqer\\Barcode\\' => 
        array (
            0 => __DIR__ . '/..' . '/picqer/php-barcode-generator/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit904435d701a1655b4dcb389c24fce1ac::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit904435d701a1655b4dcb389c24fce1ac::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
